### ISSUE TITLE
equivalences are embeddings

### ISSUE THREAD

**Issue by jonalfcam** [rzk-lang/sHoTT#102]
For a few things I want to do, it will be useful to have the statement that equivalences are embeddings in the HoTT section of the library. I'm working on this now.

**Comment by emilyriehl** [comment]
If I understand what you want correctly, this is there already:

https://rzk-lang.github.io/sHoTT/hott/04-half-adjoint-equivalences.rzk/#equivalences-are-embeddings

**Comment by jonalfcam** [comment]
Thanks. I have no idea how I missed this.

**Comment by jonalfcam** [comment]
I''ll close this out.
