### ISSUE TITLE
Formalise Theorem 8.8 of RS17 paper

### ISSUE THREAD

**Issue by fizruk** [rzk-lang/sHoTT#12]
This one would particularly benefit from the literate style, providing the category-theoretic version of the proof from the paper in the text.

**Comment by cesarbm03** [comment]
Feel free to modify the code I added if there is anything clashing with your proof.

**Comment by TashiWalde** [comment]
Let me also record here what I told @cesarbm03 .

After formalizing orthogonality and some of the statility properties thereof (see #81  and #76), it will be possible to formalize a very clean proof of this fact.

**Comment by TashiWalde** [comment]
@cesarbm03 Do you still plan to add anything to this issue or should we close it? If so, should we keep the helper methods `apply-4-3` `apply-4-3-again` `total-inner-horn-restriction` `map-to-total-inner-horn-restriction-fiber` or can they be removed?
