### ISSUE TITLE
Update the list of contributors

### ISSUE THREAD

**Issue by fizruk** [rzk-lang/sHoTT#34]
Perhaps, we should maintain a list of contributors in a single place and refer to it from wherever we have a list at the moment.

**Comment by emilyriehl** [comment]
@fizruk I'd like to take care of this issue tomorrow. I can update the readme and perhaps you can invite collaborators to the sHoTT repository? (Or if you'd rather I can do that too.) I'll include @kyoDralliam @jonalfcam @dvmcarpena @TashiWalde and @nimarasekh

**Comment by fizruk** [comment]
I've invited the following people with **Write** permissions:

- @kyoDralliam
- @jonalfcam 
- @dvmcarpena 
- @TashiWalde 
- @nimarasekh

The **Maintainer** rights are reserved for now for @emilyriehl, @jonweinb, and me.

In addition to updating a README, I think it would be good to have a list of contributors in one place, e.g. `src/CONTRIBUTORS.md` file (that would also render on the website) and link to it from README and `src/index.md`. What do you think?

**Comment by jonweinb** [comment]
Thank you @fizruk! This sounds very good to me.

**Comment by emilyriehl** [comment]
That's an even better idea.

**Comment by emilyriehl** [comment]
@fizruk I think I listed everyone [here](https://rzk-lang.github.io/sHoTT/) and I also updated the references. I'll let you make a CONTRIBUTORS.md if you want one since I wasn't sure the best way to format it anyway.

**Comment by fizruk** [comment]
The list of contributors appears to be up-to-date at <https://rzk-lang.github.io/sHoTT/CONTRIBUTORS/>.
